ALTER TABLE ezz_drivers ADD COLUMN IF NOT EXISTS total_trips INTEGER DEFAULT 0;
ALTER TABLE ezz_drivers ADD COLUMN IF NOT EXISTS total_earnings REAL DEFAULT 0;
ALTER TABLE ezz_drivers ADD COLUMN IF NOT EXISTS total_commission_paid REAL DEFAULT 0;